-- SQL SCHEMA FOR ONE VENDOR SOLUTIONS SUPABASE BACKEND
-- Copy and paste this script directly into the Supabase SQL Editor and execute.

-- 1. Create enquiries table
CREATE TABLE IF NOT EXISTS enquiries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name text NOT NULL,
    organization text,
    contact_number text NOT NULL,
    email text NOT NULL,
    category text NOT NULL,
    detailed_requirement text NOT NULL,
    preferred_date text
);

-- Enable RLS (Row Level Security) and add insertion policy
ALTER TABLE enquiries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public inserts on enquiries" ON enquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on enquiries" ON enquiries FOR SELECT USING (true);

-- 2. Create contact_messages table
CREATE TABLE IF NOT EXISTS contact_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name text NOT NULL,
    email text NOT NULL,
    phone text,
    subject text NOT NULL,
    message text NOT NULL
);

-- Enable RLS and add insertion policy
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public inserts on contact_messages" ON contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on contact_messages" ON contact_messages FOR SELECT USING (true);

-- 3. Create bookings table
CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name text NOT NULL,
    phone text NOT NULL,
    requirement_type text NOT NULL,
    date text NOT NULL,
    time_slot text NOT NULL
);

-- Enable RLS and add insertion policy
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public inserts on bookings" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on bookings" ON bookings FOR SELECT USING (true);
